### ISSUE TITLE
PostgreSQL requires a Django adapter psycopg2

### ISSUE THREAD

**Issue by sudoankit** [ShotRecords/cricbase#1]
Should we stick to `SQLite3`, the default what `Django` creates or shift to `PostgreSQL` using a `Django` adapter for it?

See more here : [psycopg2](https://pypi.python.org/pypi/psycopg2)

**Comment by abhijeetpanda12** [comment]
No, we will do it with Postgres. It's a pain in the ass, but we still have to do it.

**Comment by sudoankit** [comment]
Fine. Pain is gain. I'm closing it.
